name: Deploy Bicep Template Lab1

on: workflow_dispatch

jobs:
  deploy-bicep-template:
    runs-on: ubuntu-latest

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
  AZURE_RG: ${{ secrets.AZURE_RG }}

    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: $AZURE_CREDENTIALS

      # Deploy Bicep file
    - name: Deploy Bicep Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: $AZURE_SUBSCRIPTION
        resourceGroupName: $AZURE_RG 
        template: ./bicep/lab1/main.bicep
        parameters: mystorageAccountName=mystoragemx01
        failOnStdErr: false
